### ISSUE TITLE
No public NetworkMode setting

### ISSUE THREAD

**Issue by cameronws** [anshooarora/extentreports-csharp#4]
I see in the base Reporter class the NetworkMode property exists, but it's not publically accessible from the ExtentReports class. Is this to prevent users from changing the setting, if so, why does it even exist. I don't see why I would have to write my own implementation of the ExtentReport class just so that I can have the option of being able to change that setting.

**Comment by anshooarora** [comment]
Its not visible because this feature is yet to be implemented.  The aim of this setting is to allow users to save all the resources (js, css, fonts) along with the HTML file so the report can be accessed without internet access:

```
Extent.html
/extent
    /css
    /js
    /fonts
```

PS.  The upcoming v3 for both Java and .Net will not have this option at all.
