### ISSUE TITLE
Percentage calculation is considering tests which are skiped

### ISSUE THREAD

**Issue by NaveenAutomate** [anshooarora/extentreports-csharp#78]
Hi Anshoo,

while caluclating pass percentage , it is considering skiped test case count also. how can i get only test cases which are actually executed.

![image](https://user-images.githubusercontent.com/29267691/29079144-fda73942-7c79-11e7-9b6c-1803fe8c7bb5.png)

**Comment by anshooarora** [comment]
Its only possible by modifying the sources,  no configuration is available to do so.  In version 3, you can change [this](https://github.com/anshooarora/extentreports-csharp/blob/master/dist/js/extent.js#L456) to omit skip counts, but then you will have to change the Java sources to pick up your changed file instead of the one server by CDN.

**Comment by NaveenAutomate** [comment]
Thanks for the reply. Is it possible to make this configurable in future?

**Comment by anshooarora** [comment]
No, since even the skipped test cases must be part of the dashboard.  Looking at the overall picture, we can immediately tell how many were skipped.  If we drop these counts, the numbers will be skewed between the dashboard and the test list.
